@echo off 
rem 所有用户配置文件位置
echo %allusersprofile%
echo 默认情况应用程序存储数据的位置
echo %appdata%
rem 当前目录字符串
echo %cd%
rem 返回用来启动当前Cmd.exe的准确命令行
echo %cmdcmdline%
rem 命令处理程序扩展的版本号
echo %cmdextversion%
rem 主机名
echo %computername%
rem 命令解释器可执行程序的准确路径
echo %comspec%
rem 当前日期
echo %date%
rem 错误代码
echo %errorlevel%
rem 用户主目录的本地工作站驱动器号
echo %homedrive%
rem 用户主目录完整路径
echo %homepath%
rem 共享主目录的网络路径
echo %homeshare%
rem 当前登录会话的域控制器的名称
echo %logonserver%
rem 处理器的数目
echo %number_of_processors% 
rem 操作系统名称
echo %os%
rem 可执行文件的搜索路径
echo %path%
rem 可执行的文件扩展名的列表
echo %pathext%
rem 处理的芯片体系结构
echo %processor_architecture%
rem 处理器说明
echo %processor_identfier%
rem 处理器型号
echo %processor_level%
rem 处理器版本号
echo %processor_revision%
rem 当前解释程序的命令提示符设置。由Cmd.exe生成
rem 随机数0-32767
echo %random%
rem  系统根目录
echo %systemdrive%
rem 系统根目录位置
echo %systemroot%
rem 临时目录
echo %temp%
echo %tmp%
rem time
echo %time%
rem 用户账户域
echo %userdomain%
echo %username%
echo %userprofile%
echo %windir%

pause